### PR TITLE
Add .editorconfig and super-linter

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/10)

### CODE REVIEW

**Review by lassemaatta — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/10)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @pallost)

___
*[development.sh, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/10#-MVprY2z6K1pbDqHQ0PF:-MVprY2z6K1pbDqHQ0PG:b1ra5bc) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/204fac01742301cc89cd04e96aa735f3e269fbb1/development.sh#L2)):*
> ```Shell
> #!/bin/bash
> ```

Näissä eri bash skripteissä vois imho olla aina vähintään `set -eu` käytössä

**Review by lassemaatta — COMMENTED** [review]
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/10)* status: 20 of 21 files reviewed, 1 unresolved discussion (waiting on @lassemaatta and @pallost)

**Review by lassemaatta — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/10)* status: all files reviewed, 1 unresolved discussion (waiting on @pallost)

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/10)* status: 16 of 21 files reviewed, 1 unresolved discussion (waiting on @lassemaatta)

___
*[development.sh, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/10#-MVprY2z6K1pbDqHQ0PF:-MVpstBx9L9SkQq3nrlo:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/204fac01742301cc89cd04e96aa735f3e269fbb1/development.sh#L2)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Näissä eri bash skripteissä vois imho olla aina vähintään `set -eu` käytössä
</blockquote></details>

Done.

**Review by lassemaatta — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/10)* status: all files reviewed, 1 unresolved discussion (waiting on @lassemaatta)

**Pull request merged**
