### PR TITLE
Allow application gw access from world (0.0.0.0/0)

### PR DESCRIPTION
**Pull request by jschummer**
Also always deploy the app gw network security group, instead of
deploying it only if it previously wasn't deployed. The previous logic
was put in place to be able to configure the app gw access nsg manually
after deployment, which is not needed anymore.

Even after this change, the access subnet can still be configured in the
ansible conf. This allows changing the currently used world access to a
more limiting subnet later.

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/59)

### CODE REVIEW

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/59)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @jschummer and @pallost)

___
*[ansible/templates/network.arm.json, line 29 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/59#-MyMb6o7AaKWxnq7OEqG:-MyMb6o88hyPCfNQZFk3:bu0sr21) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/15ceeeb8dc7a9f492e0484c5cb4dbd6390ca4c5d/ansible/templates/network.arm.json#L29)):*
> ```JSON
>         "description": "The IP addresses allowed to connect to the service."
>       },
>       "defaultValue": ["0.0.0.0/0"]
> ```

as this is kind of a sensitive value, let's set a default value for it but make sure it's always explicitly set through the parameters

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/59)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @pallost)

___
*[ansible/templates/network.arm.json, line 29 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/59#-MyMb6o7AaKWxnq7OEqG:-MyMbqKY2vbIeDe2W-q2:bbnkdhv) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/15ceeeb8dc7a9f492e0484c5cb4dbd6390ca4c5d/ansible/templates/network.arm.json#L29)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

as this is kind of a sensitive value, let's set a default value for it but make sure it's always explicitly set through the parameters
</blockquote></details>

I'm not sure I understand. Do you think the default value should come from outside this template?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/59)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @jschummer and @pallost)

___
*[ansible/templates/network.arm.json, line 29 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/59#-MyMb6o7AaKWxnq7OEqG:-MyMcMJh1GTMuUOSeVuq:b7kclb8) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/15ceeeb8dc7a9f492e0484c5cb4dbd6390ca4c5d/ansible/templates/network.arm.json#L29)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

I'm not sure I understand. Do you think the default value should come from outside this template?
</blockquote></details>

no, I mean there shouldn't be a default value set here in the ARM template, let's just remove this line and also maybe the from the bastionTrustedAddresses. So if we forget to set these values for some reason, the playbook would fail

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/59)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @pallost)

___
*[ansible/templates/network.arm.json, line 29 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/59#-MyMb6o7AaKWxnq7OEqG:-MyMcsQYEXbNiIp271J5:brf2z0v) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/15ceeeb8dc7a9f492e0484c5cb4dbd6390ca4c5d/ansible/templates/network.arm.json#L29)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

no, I mean there shouldn't be a default value set here in the ARM template, let's just remove this line and also maybe the from the bastionTrustedAddresses. So if we forget to set these values for some reason, the playbook would fail
</blockquote></details>

Yes, that's what I tried to say - that the default value should be defined outside this template. E.g. only in `az_gateway_trusted_ips` in `all.yml`. Does that sound right?

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/59)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @pallost)

___
*[ansible/templates/network.arm.json, line 29 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/59#-MyMb6o7AaKWxnq7OEqG:-MyMeG2I94BzInOdxPTI:bmsqcwh) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/15ceeeb8dc7a9f492e0484c5cb4dbd6390ca4c5d/ansible/templates/network.arm.json#L29)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Yes, that's what I tried to say - that the default value should be defined outside this template. E.g. only in `az_gateway_trusted_ips` in `all.yml`. Does that sound right?
</blockquote></details>

Now also added a separate commit to remove the default value of the bastion host trusted addresses. I btw somewhat disagree that the address space from which the service is reachable would be a particularly sensitive setting. But I don't have any good reason to keep the default in here, so I removed it.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/59)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @pallost)

**Pull request merged**
