### PR TITLE
Enable access to bastion host from Vincit's office network

### PR DESCRIPTION
**Pull request by tk-vincit**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/19)

### CODE REVIEW

**Review by jschummer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/19)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @pallost and @tk-vincit)

*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-deploy/19#-MWSvdHNErICW36zRa-z:-MWSvdHO0lDmut7avrtB:b-ok4upz) (no related file):*
Niin kuin slackissa mainittu jo, tätä voisi joskus pohtia vielä uudestaan, jotta ei Vincitiläiset voisivat päästä näihin kiinni ilman (Vinicitin) VPN:ää.

Mutta ei tokikaan tämän PR:n scopessa, yleisenä kommenttina vaan :+1: 

---
___
*[ansible/vars/env-test.yml, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/19#-MWSv1_g1NyFIO79uwQZ:-MWSv1_h9e6gcuk8VaBd:b-kkmklx) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8201250b9a7d26a1fb7359c7081f30e46039091d/ansible/vars/env-test.yml#L16)):*
> ```
> 213.255.177.137/32
> ```
Lisäätkö tämän saman rivin vielä env-dev.yml:iin?

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/19)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jschummer and @tk-vincit)

___
*[ansible/vars/env-test.yml, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/19#-MWSv1_g1NyFIO79uwQZ:-MWTN-vLBVb9MEqa87xL:b-nusih9) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8201250b9a7d26a1fb7359c7081f30e46039091d/ansible/vars/env-test.yml#L16)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> 213.255.177.137/32
> ```
Lisäätkö tämän saman rivin vielä env-dev.yml:iin?
</blockquote></details>

and to `env-prod` as well :)

**Review by pallost — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/19)* status: all files reviewed, 2 unresolved discussions (waiting on @jschummer and @tk-vincit)

**Review by tk-vincit — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/19)* status: all files reviewed, 2 unresolved discussions (waiting on @jschummer)

*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-deploy/19#-MWSvdHNErICW36zRa-z:-MWU7kzZ5woa-klcgeje:bb6un1j) (no related file):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Niin kuin slackissa mainittu jo, tätä voisi joskus pohtia vielä uudestaan, jotta ei Vincitiläiset voisivat päästä näihin kiinni ilman (Vinicitin) VPN:ää.

Mutta ei tokikaan tämän PR:n scopessa, yleisenä kommenttina vaan :+1: 
</blockquote></details>

Done

---
___
*[ansible/vars/env-test.yml, line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/19#-MWSv1_g1NyFIO79uwQZ:-MWU7mVz4Vg7Cic5XUva:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/8201250b9a7d26a1fb7359c7081f30e46039091d/ansible/vars/env-test.yml#L16)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

and to `env-prod` as well :)
</blockquote></details>

Done

**Pull request merged**
