### PR TITLE
Secret mapping

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/23)

### CODE REVIEW

**Review by lassemaatta — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/23)* status: all files reviewed, 2 unresolved discussions (waiting on @jschummer, @pallost, and @tk-vincit)

___
*[clusters/base/hsl-jore4/jore4-backend.yaml, line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/23#-MWxTnvS3CjdvKsQxW2G:-MWxTnvS3CjdvKsQxW2H:b-6mzqnh) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/b9a2634acbd98a860fdd475d3b09cf39c95f187e/clusters/base/hsl-jore4/jore4-backend.yaml#L34)):*
> ```YAML
>             volumeAttributes:
>               secretProviderClass: "jore4-backend-secret-mapping"
> ---
> ```

Would it be possible to map the paths of the individual secrets (e.g. `/mnt/secrets-store/db-username`) to environmental variables (`DB_USERNAME_PATH`) and thus provide an additional layer of indirection?
___
*[clusters/base/hsl-jore4/jore4-backend.yaml, line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/23#-MWxUiJ1CrfYMGWtOJ0L:-MWxUiJ1CrfYMGWtOJ0M:bspr6j7) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/b9a2634acbd98a860fdd475d3b09cf39c95f187e/clusters/base/hsl-jore4/jore4-backend.yaml#L35)):*
> ```
> mapping secret mapping class
> ```

Is the word _mapping_ here twice intentionally?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/23)* status: all files reviewed, 2 unresolved discussions (waiting on @jschummer, @lassemaatta, and @tk-vincit)

___
*[clusters/base/hsl-jore4/jore4-backend.yaml, line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/23#-MWxTnvS3CjdvKsQxW2G:-MWxZpbh6mASxwzFZX4N:b5n5ho) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/b9a2634acbd98a860fdd475d3b09cf39c95f187e/clusters/base/hsl-jore4/jore4-backend.yaml#L34)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Would it be possible to map the paths of the individual secrets (e.g. `/mnt/secrets-store/db-username`) to environmental variables (`DB_USERNAME_PATH`) and thus provide an additional layer of indirection?
</blockquote></details>

it would be possible but in the concept of secret-files, the `db-username` here is already a constant. I don't really see a point to create a `DB_USERNAME_PATH` constant to point at the `db-username` constant to retrieve the actual secret value. What kind of attack would this save us from...?
___
*[clusters/base/hsl-jore4/jore4-backend.yaml, line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/23#-MWxUiJ1CrfYMGWtOJ0L:-MWx_Tge-pwMQe-6YWx2:b-2szq21) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/b9a2634acbd98a860fdd475d3b09cf39c95f187e/clusters/base/hsl-jore4/jore4-backend.yaml#L35)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> mapping secret mapping class
> ```

Is the word _mapping_ here twice intentionally?
</blockquote></details>

kinda, but I admit it looks funny. Let's just have it as "secret mapping class" :)

**Review by lassemaatta — APPROVED** [review]
Looks ok to me, but someone who understands this better might want to take a look (@jschummer?).

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/23#-:-MWxpCYE9JbExxJETywO:b-mk1bez)* status: all files reviewed, 2 unresolved discussions (waiting on @jschummer, @lassemaatta, and @tk-vincit)

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/23)* status: all files reviewed, 2 unresolved discussions (waiting on @jschummer, @lassemaatta, and @tk-vincit)

___
*[clusters/base/hsl-jore4/jore4-backend.yaml, line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/23#-MWxTnvS3CjdvKsQxW2G:-MX0f3Dw6003cILXzcgf:bzgolbt) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/b9a2634acbd98a860fdd475d3b09cf39c95f187e/clusters/base/hsl-jore4/jore4-backend.yaml#L34)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it would be possible but in the concept of secret-files, the `db-username` here is already a constant. I don't really see a point to create a `DB_USERNAME_PATH` constant to point at the `db-username` constant to retrieve the actual secret value. What kind of attack would this save us from...?
</blockquote></details>

as a temporary measure, I added a `SECRET_STORE_BASE_PATH` environment variable to point at `/mnt/secrets-store`. It requires less maintenance. If required, later we could add per-secret path pointing env variables also...
___
*[clusters/base/hsl-jore4/jore4-backend.yaml, line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/23#-MWxUiJ1CrfYMGWtOJ0L:-MX0fLB0DZWcl_rk9M6r:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/b9a2634acbd98a860fdd475d3b09cf39c95f187e/clusters/base/hsl-jore4/jore4-backend.yaml#L35)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

kinda, but I admit it looks funny. Let's just have it as "secret mapping class" :)
</blockquote></details>

Done.

**Review by jschummer — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/23)* status: all files reviewed, 2 unresolved discussions (waiting on @lassemaatta and @tk-vincit)

**Pull request merged**
