### PR TITLE
Deletion protection for resource groups in prod, test environments

### PR DESCRIPTION
**Pull request by jschummer**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18)

### CODE REVIEW

**Review by lassemaatta — APPROVED** [review]
Looks fine to me, but perhaps @pallost should check this out too.

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-:-MWTPbLqCs6DJ5Fa3zzn:brk8m4o)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschummer)

**Review by jschummer — COMMENTED** [review]
Could actually add some randomish change to either commit (even though Tamas approves), just to see myself how "review each commit separately" works...

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-:-MWTwDKg8MaVdCMiYtDn:bcqfgcu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschummer)

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @jschummer and @lassemaatta)

___
*[README.md, line 115 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWTzuTX43LJop9Pq811:-MWTzuTX43LJop9Pq812:bhw10xb) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/README.md#L115)):*
> ```Markdown
>   secrets, DEV Kubernetes cluster, DEV database)
> - resources in the `hsl-jore4-test` and `hsl-jore4-prod` resource groups (created using the
>   `playtest` or `playprod` aliases) as well as resources in the `hsl-jore4-common` resource group
> ```

actually right now I only see that the network is protected by the lock. Have you btw tried setting `az_critical_tag_default` to "yes" for the test and prod resource groups, would that enable deletion protection for all the resources inside instead of manually setting the lock for each and every resource in the group?
___
*[README.md, line 121 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWTyeJT1UvELWtq-m6A:-MWTyeJT1UvELWtq-m6B:bdas2cp) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/README.md#L121)):*
> ```Markdown
> - use the Owner-role in order to remove the lock and to be able to delete resources
> - for more information on the locking mechanism and on how to use the Owner-role, see the
>   [HSL Azure dashboard](https://portal.azure.com/#@hslfi.onmicrosoft.com/dashboard/arm/subscriptions/b13714ed-2c1b-416c-89a9-909524515193/resourcegroups/dashboards/providers/microsoft.portal/dashboards/bcea8162-492c-4428-ba8c-19321eceb0cd)
> ```

you could actually just link to the existing section that's already explaining roles: `[Roles](#roles)`
___
*[ansible/roles/azure_network/tasks/main.yml, line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWTyy8zEbyuuipDIXBY:-MWTyy8zEbyuuipDIXBZ:b-oxjdjo) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/ansible/roles/azure_network/tasks/main.yml#L25)):*
> ```YAML
>       privateRouteTableName:
>         value: "{{ az_private_route_table_name }}"
>       enableDeletionProtection:
> ```

I'd actually just combine the "critical" tag with this "lock" tag. So instead of having `az_enable_deletion_protection` and `az_critical_tag_default`, maybe could leave the `az_enable_deletion_protection`
___
*[ansible/templates/network.arm.json, line 129 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWU-Ay1ANZjEC3cApfF:-MWU-Ay1ANZjEC3cApfG:bfipypn) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/ansible/templates/network.arm.json#L129)):*
> ```JSON
>   "resources": [
>     {
>       "type": "Microsoft.Resources/tags",
> ```

I don't really see where these tags are actually attached when they are created as a separate resource.. wouldn't it be clearer if you added it to the virtualNetworks resource below?
```
    {
      "type": "Microsoft.Network/virtualNetworks",
      ...
      "tags": "[if(parameters('enableDeletionProtection'),json('{ \"lock\": \"cannotdelete\" }'),json('{}'))]"
    }
```
___
*[ansible/templates/network.arm.json, line 133 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWU--JB3_FzGxBoIZzM:-MWU--JB3_FzGxBoIZzN:b-ssnc17) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/ansible/templates/network.arm.json#L133)):*
> ```JSON
>       "apiVersion": "2020-06-01",
>       "properties": {
>         "tags": "[if(parameters('enableDeletionProtection'),json('{ \"lock\": \"cannotdelete\" }'),json('{}'))]"
> ```

is this overwriting the `ansible: workaround` tag in the `main.yaml`? or is it extending it?

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @lassemaatta and @pallost)

___
*[README.md, line 115 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWTzuTX43LJop9Pq811:-MWUDFnl8ZGAaUUxzi2L:b-x6qsog) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/README.md#L115)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

actually right now I only see that the network is protected by the lock. Have you btw tried setting `az_critical_tag_default` to "yes" for the test and prod resource groups, would that enable deletion protection for all the resources inside instead of manually setting the lock for each and every resource in the group?
</blockquote></details>

The lock is applied to the whole resource group and all its resources (even though the _tag_ is only applied to the rg itself). A quick look at the portal seems to confirm that.

I didn't try the critical tag, since the dashboard explicitly mentions the lock-tag. Because of that I think it's the best solution to use that tag.
___
*[README.md, line 121 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWTyeJT1UvELWtq-m6A:-MWUCwFR4JZ3d9pFm_MX:byhw0s4) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/README.md#L121)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you could actually just link to the existing section that's already explaining roles: `[Roles](#roles)`
</blockquote></details>

Good point, I'll just replace that with a reference to the roles-section.
___
*[ansible/roles/azure_network/tasks/main.yml, line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWTyy8zEbyuuipDIXBY:-MWUEOBaEVfTqrCZWCpY:b401q8x) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/ansible/roles/azure_network/tasks/main.yml#L25)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd actually just combine the "critical" tag with this "lock" tag. So instead of having `az_enable_deletion_protection` and `az_critical_tag_default`, maybe could leave the `az_enable_deletion_protection`
</blockquote></details>

Apparently the dashboard mentions that the "critical"-tag is deprecated now. So in that sense it makes sense to get rid of it.

I think the best way to do that is to create a separate commit in this PR, will do that.
___
*[ansible/templates/network.arm.json, line 129 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWU-Ay1ANZjEC3cApfF:-MWUEone9icCS1s12SRF:b1r1k0e) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/ansible/templates/network.arm.json#L129)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I don't really see where these tags are actually attached when they are created as a separate resource.. wouldn't it be clearer if you added it to the virtualNetworks resource below?
```
    {
      "type": "Microsoft.Network/virtualNetworks",
      ...
      "tags": "[if(parameters('enableDeletionProtection'),json('{ \"lock\": \"cannotdelete\" }'),json('{}'))]"
    }
```
</blockquote></details>

If tags are created as separate resources they are applied to the resource group, because the ARM template is apparently (usually?) targeted at the resource group. And if the lock-tag is applied to the resource group, that will create the lock at rg level, so it'll protect all of the rg's resources.

I figured it makes more sense to apply the tag to the whole resource group instead of just the vnets. Because if everything else (except the vnet) is deleted, that is not a good situation.
___
*[ansible/templates/network.arm.json, line 133 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWU--JB3_FzGxBoIZzM:-MWUGbYW7wAJqIgUVQee:blclc82) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/ansible/templates/network.arm.json#L133)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

is this overwriting the `ansible: workaround` tag in the `main.yaml`? or is it extending it?
</blockquote></details>

The `ansible: workaround` tag is not applied at resource level, so it will not interfere with it.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @jschummer, @lassemaatta, and @pallost)

___
*[README.md, line 115 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWTzuTX43LJop9Pq811:-MWUOZ1j1CE4nQEybj05:bpqwaen) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/README.md#L115)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

The lock is applied to the whole resource group and all its resources (even though the _tag_ is only applied to the rg itself). A quick look at the portal seems to confirm that.

I didn't try the critical tag, since the dashboard explicitly mentions the lock-tag. Because of that I think it's the best solution to use that tag.
</blockquote></details>

yeah, I realised that this actuall works on the resource group level, all good!
___
*[ansible/roles/azure_network/tasks/main.yml, line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWTyy8zEbyuuipDIXBY:-MWUOVAe9aPZnf_d_omy:bhma55a) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/ansible/roles/azure_network/tasks/main.yml#L25)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Apparently the dashboard mentions that the "critical"-tag is deprecated now. So in that sense it makes sense to get rid of it.

I think the best way to do that is to create a separate commit in this PR, will do that.
</blockquote></details>

sure, let's do it in another PR!
___
*[ansible/templates/network.arm.json, line 129 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWU-Ay1ANZjEC3cApfF:-MWUOj2wCkAuct80gxwJ:bihaxxp) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/ansible/templates/network.arm.json#L129)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

If tags are created as separate resources they are applied to the resource group, because the ARM template is apparently (usually?) targeted at the resource group. And if the lock-tag is applied to the resource group, that will create the lock at rg level, so it'll protect all of the rg's resources.

I figured it makes more sense to apply the tag to the whole resource group instead of just the vnets. Because if everything else (except the vnet) is deleted, that is not a good situation.
</blockquote></details>

yeah, it's good if you apply the tag to the whole resource group :+1: 
however this tag does not belong to the `network.arm.json`

You could e.g. modify the `roles/azure_resourcegroup-main.yaml` script that it places the tag instead of this arm template. (The `critical` tag is already done like this) Or if that doesn't work, then should maybe create a separate `tags.arm.json` template that's sole job is to apply the tag to the resource group

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @lassemaatta and @pallost)

___
*[README.md, line 115 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWTzuTX43LJop9Pq811:-MWUQ2JiC0axkhJZjxpO:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/README.md#L115)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

yeah, I realised that this actuall works on the resource group level, all good!
</blockquote></details>

Done.
___
*[ansible/roles/azure_network/tasks/main.yml, line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWTyy8zEbyuuipDIXBY:-MWUQ3LMB6R91tunlddn:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/ansible/roles/azure_network/tasks/main.yml#L25)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

sure, let's do it in another PR!
</blockquote></details>

Done.
___
*[ansible/templates/network.arm.json, line 129 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWU-Ay1ANZjEC3cApfF:-MWUQ4m4AQVFpgpAP_Px:b-rbg263) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/ansible/templates/network.arm.json#L129)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

yeah, it's good if you apply the tag to the whole resource group :+1: 
however this tag does not belong to the `network.arm.json`

You could e.g. modify the `roles/azure_resourcegroup-main.yaml` script that it places the tag instead of this arm template. (The `critical` tag is already done like this) Or if that doesn't work, then should maybe create a separate `tags.arm.json` template that's sole job is to apply the tag to the resource group
</blockquote></details>

True, it's probably the wrong file. I'll check and use one of the solutions you suggested. :+1:

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @lassemaatta and @pallost)

___
*[ansible/templates/network.arm.json, line 133 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWU--JB3_FzGxBoIZzM:-MWUQKzH4JkhDnsnaFWf:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/ansible/templates/network.arm.json#L133)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

The `ansible: workaround` tag is not applied at resource level, so it will not interfere with it.
</blockquote></details>

Done.

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @lassemaatta and @pallost)

___
*[ansible/templates/network.arm.json, line 129 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWU-Ay1ANZjEC3cApfF:-MW_RTGO2KWC9dZ6i3fs:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/0a8988d796fed29c85f741fd69411401931b4138/ansible/templates/network.arm.json#L129)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

True, it's probably the wrong file. I'll check and use one of the solutions you suggested. :+1: 
</blockquote></details>

Done.

**Review by pallost — APPROVED** [review]
> Reviewed 2 of 7 files at r4, 2 of 7 files at r5, 4 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @jschummer and @pallost)

___
*[README.md, line 134 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWZ2zpFBflfoEtP67Kf:-MWZ2zpFBflfoEtP67Kg:bloypqp) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/865112cdb195e3feb50a4d90311a3109b2206545/README.md#L134)):*
> ```Markdown
> - use the Owner-role in order to remove the lock and to be able to delete resources
> - for more information on the locking mechanism and on how to use the Owner-role, see the
>   [HSL Azure dashboard](https://portal.azure.com/#@hslfi.onmicrosoft.com/dashboard/arm/subscriptions/b13714ed-2c1b-416c-89a9-909524515193/resourcegroups/dashboards/providers/microsoft.portal/dashboards/bcea8162-492c-4428-ba8c-19321eceb0cd)
> ```

it's no biggie, but did you mean to reference the "Roles" section in this same README instead?
___
*[ansible/roles/azure_resourcegroup/tasks/main.yml, line 22 at r6](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWcN6QRBuAIxOwHIlBG:-MWcN6QSEljxujciwSEy:b-7m74ox) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5f1087ddbfec3f70d9af6d1a82de11b8930109ee/ansible/roles/azure_resourcegroup/tasks/main.yml#L22)):*
> ```YAML
>   set_fact:
>     tags: "{{ tags | combine({ \"lock\": \"cannotdelete\" }) }}"
>   when: az_enable_deletion_protection == true
> ```

nice!
___
*[ansible/roles/azure_resourcegroup/tasks/main.yml, line 32 at r6](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWcNNPj8_9H2Qej5I--:-MWcNNPj8_9H2Qej5I-0:b-lhmkp) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5f1087ddbfec3f70d9af6d1a82de11b8930109ee/ansible/roles/azure_resourcegroup/tasks/main.yml#L32)):*
> ```YAML
>     location: "{{ az_region_name }}"
>     tags: "{{ tags }}"
>     append_tags: false
> ```

good that you also noticed and used the "append_tags" parameter

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[README.md, line 134 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWZ2zpFBflfoEtP67Kf:-MWhjTL9AZw9PkuIdenO:b-13lqs0) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/865112cdb195e3feb50a4d90311a3109b2206545/README.md#L134)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it's no biggie, but did you mean to reference the "Roles" section in this same README instead?
</blockquote></details>

Didn't I reference the "Roles" section? :grimacing: 
___
*[ansible/roles/azure_resourcegroup/tasks/main.yml, line 22 at r6](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWcN6QRBuAIxOwHIlBG:-MWhjRCL1GhSBFda5Gsv:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5f1087ddbfec3f70d9af6d1a82de11b8930109ee/ansible/roles/azure_resourcegroup/tasks/main.yml#L22)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

nice!
</blockquote></details>

Done.
___
*[ansible/roles/azure_resourcegroup/tasks/main.yml, line 32 at r6](https://reviewable.io/reviews/hsldevcom/jore4-deploy/18#-MWcNNPj8_9H2Qej5I--:-MWhjR_9AdQocUauj0TS:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5f1087ddbfec3f70d9af6d1a82de11b8930109ee/ansible/roles/azure_resourcegroup/tasks/main.yml#L32)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

good that you also noticed and used the "append_tags" parameter
</blockquote></details>

Done.

**Pull request merged**
