### PR TITLE
Gateway ip filter

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/35)

Closes https://github.com/HSLdevcom/jore4/issues/109

### CODE REVIEW

**Review by lassemaatta — COMMENTED** [review]
Looks fine to me, but on the other hand I don't understand any of this :)

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/35#-:-MZBx0vN0QzbtRXUnQmJ:b8wz7xn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschummer)

**Review by jschummer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/35)* status: all files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[README.md, line 125 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/35#-MZGvhgR3EARg_6HSSjx:-MZGvhgR3EARg_6HSSjy:br41f8l) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/aa1c5d8cf47af573edc2428e7b69316aa362378d/README.md#L125)):*
> ```
>  Exception
> ```
should probably be "Exceptions" with 's' in the end
___
*[ansible/roles/azure_network/tasks/main.yml, line 8 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/35#-MZHJZoh71HCGGdBhpSL:-MZHJZoh71HCGGdBhpSM:b-p7sp8y) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/aa1c5d8cf47af573edc2428e7b69316aa362378d/ansible/roles/azure_network/tasks/main.yml#L8)):*
> ```
>  'az network nsg list --resource-group {{ az_resource_group_name }} --query "[?name==''{{ az_public_nsg_name }}''].{id:id}[0].id"'
> ```
I'd rather see changes not _directly_ related to the core change in a separate commit.

Since this seems to be the only such change, I think you can leave it here. I'll let you get away with it this time ;-)
___
*[ansible/roles/azure_network/tasks/main.yml, line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/35#-MZHLTY0DyyQLT1qL_F-:-MZHLTY0DyyQLT1qL_F0:b-6jrpuo) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/aa1c5d8cf47af573edc2428e7b69316aa362378d/ansible/roles/azure_network/tasks/main.yml#L21)):*
> ```
> Deploy public NSG: {{ deploy_public_nsg }}; Deploy gateway NSG: {{ deploy_gateway_nsg }}
> ```
For debugging purposes, I think displaying the actual ID is more useful. Is there a reason to hide it from the user?

**Review by jschummer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/35)* status: all files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[ansible/roles/azure_network/tasks/main.yml, line 8 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/35#-MZHJZoh71HCGGdBhpSL:-MZHN49b73zlS6OwuwWO:bb21739) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/aa1c5d8cf47af573edc2428e7b69316aa362378d/ansible/roles/azure_network/tasks/main.yml#L8)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
>  'az network nsg list --resource-group {{ az_resource_group_name }} --query "[?name==''{{ az_public_nsg_name }}''].{id:id}[0].id"'
> ```
I'd rather see changes not _directly_ related to the core change in a separate commit.

Since this seems to be the only such change, I think you can leave it here. I'll let you get away with it this time ;-)
</blockquote></details>

On the other hand: Would it be an option to revert this commit when we have proper auth implemented? In that case it would be better to put this change into a separate commit. Maybe some other places (see below) could also be double-checked for "revertability"?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/35)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @jschummer and @lassemaatta)

___
*[README.md, line 125 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/35#-MZGvhgR3EARg_6HSSjx:-MZHunOD0KFN6J1be5mM:b-7ql1td) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/aa1c5d8cf47af573edc2428e7b69316aa362378d/README.md#L125)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
>  Exception
> ```
should probably be "Exceptions" with 's' in the end
</blockquote></details>

fixed
___
*[ansible/roles/azure_network/tasks/main.yml, line 8 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/35#-MZHJZoh71HCGGdBhpSL:-MZHuLBxBkIZ54kJbVNk:bykz1zz) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/aa1c5d8cf47af573edc2428e7b69316aa362378d/ansible/roles/azure_network/tasks/main.yml#L8)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

On the other hand: Would it be an option to revert this commit when we have proper auth implemented? In that case it would be better to put this change into a separate commit. Maybe some other places (see below) could also be double-checked for "revertability"?
</blockquote></details>

It's my IDE that did this, not me :) If you revert this commit, the IP filter for the App Gateway will be reverted, but the bastion host IP filter will still be in place.. as intended
___
*[ansible/roles/azure_network/tasks/main.yml, line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/35#-MZHLTY0DyyQLT1qL_F-:-MZHtzpq5q34xl0_ta9M:b-fqbmpm) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/aa1c5d8cf47af573edc2428e7b69316aa362378d/ansible/roles/azure_network/tasks/main.yml#L21)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> Deploy public NSG: {{ deploy_public_nsg }}; Deploy gateway NSG: {{ deploy_gateway_nsg }}
> ```
For debugging purposes, I think displaying the actual ID is more useful. Is there a reason to hide it from the user?
</blockquote></details>

There's no reason to hide it... I changed it like this because to me it feels that the fact the will this be redeployed is more useful to the user than what the ID of the subnet is :D Well, do you want me to print these both?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/35)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @jschummer and @lassemaatta)

___
*[ansible/roles/azure_network/tasks/main.yml, line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/35#-MZHLTY0DyyQLT1qL_F-:-MZHxP_ZE91GkZzsflNj:b6cv4n1) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/aa1c5d8cf47af573edc2428e7b69316aa362378d/ansible/roles/azure_network/tasks/main.yml#L21)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

There's no reason to hide it... I changed it like this because to me it feels that the fact the will this be redeployed is more useful to the user than what the ID of the subnet is :D Well, do you want me to print these both?
</blockquote></details>

I ended up printing them both

**Review by jschummer — APPROVED** [review]
Looking good now, green light from my side :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/35#-:-MZIB0OYEYELyNJqykw8:bo80qm1)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @lassemaatta)

___
*[ansible/roles/azure_network/tasks/main.yml, line 8 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/35#-MZHJZoh71HCGGdBhpSL:-MZIATru3TTh_DgL739H:b5a2v58) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/aa1c5d8cf47af573edc2428e7b69316aa362378d/ansible/roles/azure_network/tasks/main.yml#L8)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

It's my IDE that did this, not me :) If you revert this commit, the IP filter for the App Gateway will be reverted, but the bastion host IP filter will still be in place.. as intended
</blockquote></details>

Heh, maybe it'd still be better to keep that kind of change out of the commit then, even if you didn't add it intentionally. But you're right that in that sense it doesn't matter so much if you don't mind that line being reverted later. :+1:

**Pull request merged**
