### PR TITLE
Automatic deployment to Kubernetes with Flux

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9)

### CODE REVIEW

**Review by lassemaatta — CHANGES_REQUESTED** [review]
> Reviewed 28 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9)* status: all files reviewed, 8 unresolved discussions (waiting on @pallost)

___
*[kubernetes.sh, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpvC3p8g2E8vcXVR22:-MVpvC3p8g2E8vcXVR23:bgj1kwi) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/kubernetes.sh#L2)):*
> ```Shell
> #!/bin/bash
> ```

Näihinkin vois iskeä sitä `set -eu`:ta
___
*[kubernetes.sh, line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpvOBg1R1bfOYsemU1:-MVpvOBg1R1bfOYsemU2:b-cnkpfq) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/kubernetes.sh#L13)):*
> ```
> Should log in to the correct environment!
> ```

Jos mahdollista niin tämmöisissä tilanteissa voisi aina tulostaa mikä tuo saatu arvo oli ja mihin sitä verrattiin.
___
*[kubernetes.sh, line 48 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpw-L1DQjSXvQD-N07:-MVpw-L1DQjSXvQD-N08:bshzu9t) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/kubernetes.sh#L48)):*
> ```
> ····
> ```

Tuo lintteri-commit varmaan osaisi siivota pois tämmöiset trailing whitespacet?
___
*[README.md, line 422 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpwWtH-Fi5mxjgJp7t:-MVpwWtH-Fi5mxjgJp7u:bu64waq) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/README.md#L422)):*
> ```
> on
> ```
own
___
*[README.md, line 425 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpwbTU1vsRFXTOA3w5:-MVpwbTU1vsRFXTOA3w6:b-2jay7c) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/README.md#L425)):*
> ```
> the 
> ```

tästä puuttunee joku sana
___
*[README.md, line 429 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpwkmC2TySr8_HKqkQ:-MVpwkmC2TySr8_HKqkR:b-3ht8il) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/README.md#L429)):*
> ```
> backdraw
> ```
drawback
___
*[README.md, line 431 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpx3k0DgoDytqmcddN:-MVpx3k0DgoDytqmcddO:b3v2pia) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/README.md#L431)):*
> ```
> version in the git/helm/docker repositories
> ```

Mun mielestä tää on just miten tämän kuuluukin toimia :)
___
*[README.md, line 457 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpy-5bCOeCMzmdIL3h:-MVpy-5bCOeCMzmdIL3i:b93d05n) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/README.md#L457)):*
> ```Markdown
> 
> #### Installing Flux to the cluster
> ```

Tässä voisi tarkentaa, että onko tämä sellainen operaatio joka tehdään kerran projektin alussa vai pitääkö tätä tehdä joskus myöhemminkin uudestaan (esim jos fluxin konffeja muutetaan tms?)?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9)* status: 23 of 30 files reviewed, 8 unresolved discussions (waiting on @lassemaatta)

___
*[kubernetes.sh, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpvC3p8g2E8vcXVR22:-MW-JC_NDePqAwddhSTi:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/kubernetes.sh#L2)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Näihinkin vois iskeä sitä `set -eu`:ta
</blockquote></details>

Done.
___
*[kubernetes.sh, line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpvOBg1R1bfOYsemU1:-MW-JF7MBoUUW1ZbkY17:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/kubernetes.sh#L13)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> Should log in to the correct environment!
> ```

Jos mahdollista niin tämmöisissä tilanteissa voisi aina tulostaa mikä tuo saatu arvo oli ja mihin sitä verrattiin.
</blockquote></details>

Done.
___
*[kubernetes.sh, line 48 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpw-L1DQjSXvQD-N07:-MW-JJfu28Izer43ItI6:b-urt3dk) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/kubernetes.sh#L48)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> ····
> ```

Tuo lintteri-commit varmaan osaisi siivota pois tämmöiset trailing whitespacet?
</blockquote></details>

where do you see trailing whitespaces?
___
*[README.md, line 422 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpwWtH-Fi5mxjgJp7t:-MW-JUju51xRuJ62TAJ-:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/README.md#L422)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> on
> ```
own
</blockquote></details>

Done.
___
*[README.md, line 425 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpwbTU1vsRFXTOA3w5:-MW-Je5dDkwLD6TSSk2z:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/README.md#L425)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> the 
> ```

tästä puuttunee joku sana
</blockquote></details>

Done.
___
*[README.md, line 429 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpwkmC2TySr8_HKqkQ:-MW-JgaW3bj97w5mGCYQ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/README.md#L429)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> backdraw
> ```
drawback
</blockquote></details>

Done.
___
*[README.md, line 431 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpx3k0DgoDytqmcddN:-MW-NaU64mwuHfVaKnoB:bqx9gql) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/README.md#L431)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> version in the git/helm/docker repositories
> ```

Mun mielestä tää on just miten tämän kuuluukin toimia :)
</blockquote></details>

I try to rephrase the issue, let's see if it's more clear now :)
___
*[README.md, line 457 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpy-5bCOeCMzmdIL3h:-MW-K0iG4jrfVsMGKB11:bsdll77) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/README.md#L457)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Tässä voisi tarkentaa, että onko tämä sellainen operaatio joka tehdään kerran projektin alussa vai pitääkö tätä tehdä joskus myöhemminkin uudestaan (esim jos fluxin konffeja muutetaan tms?)?
</blockquote></details>

The Concept section already tell about the "How to", but I'll try to rephrase it. Could you check it again?

**Review by jschummer — CHANGES_REQUESTED** [review]
Maybe you could also add a reference in the commit message to which files have been generated by the flux bootstrapping thingy, i.e. list the dir / files which shouldn't be normally modified manually?

> Reviewed 3 of 5 files at r2, 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-:-MW35sxb5Ni74wvDxwNw:b-tdjam8)* status: all files reviewed, 12 unresolved discussions (waiting on @lassemaatta and @pallost)

___
*[kubernetes.sh, line 16 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MW32iqa02d6FEpbq8cT:-MW32iqb5DMig9TFywAe:blisdyl) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/29e6a1945301a733f607c8c8d4133590bd3d95af/kubernetes.sh#L16)):*
> ```
> $(kubectl config current-context)
> ```
Slightly cleaner solution would be to run the command once and store the output in a variable.
___
*[README.md, line 439 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MW33YF20XdSV0XHCP6N:-MW33YF20XdSV0XHCP6O:bo7k83n) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/29e6a1945301a733f607c8c8d4133590bd3d95af/README.md#L439)):*
> ```
> periodically
> ```
Would maybe good to state the interval. 1s, 5s, 1 min, 60 h? May make a big difference.
___
*[README.md, line 466 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MW33slC7rH0DthHgxSi:-MW33slC7rH0DthHgxSj:bx161qg) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/29e6a1945301a733f607c8c8d4133590bd3d95af/README.md#L466)):*
> ```
> :dev/:test/:prod)
> ```
I'd prefere if we could make this work without general release docker tags. So instead of deploying tag :prod over and over again, we'd explicitly update the kube config to first deploy tag :prod-1.0, then later :prod-1.1 and so on.

Is this possible? If so, could you update this example?
___
*[README.md, line 477 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MW34HVG9Q2ggokcjGAO:-MW34HVG9Q2ggokcjGAP:b-9lxxii) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/29e6a1945301a733f607c8c8d4133590bd3d95af/README.md#L477)):*
> ```Markdown
> - flux cli (https://fluxcd.io/)
> 
> This git repository already has all the Kubernetes resources bootstrapped to set up Flux to DEV,
> ```

Maybe could specify which is the directory containing the bootstrapped files, i.e. which contents shouldn't be modified manually?

**Review by lassemaatta — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9)* status: all files reviewed, 5 unresolved discussions (waiting on @pallost)

___
*[kubernetes.sh, line 48 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpw-L1DQjSXvQD-N07:-MW3DAmWA4AHrQ8t43cf:bpu4c38) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/kubernetes.sh#L48)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

where do you see trailing whitespaces?
</blockquote></details>

In the previous revision reviewable rendered "..." which I assume meant that there was unnecessary whitespace on an empty line. But now it seems it's gone in the latest revision.

**Review by lassemaatta — COMMENTED** [review]
> Reviewed 2 of 5 files at r2, 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9)* status: all files reviewed, 5 unresolved discussions (waiting on @pallost)

**Review by pallost — COMMENTED** [review]
I thought it was clear based on the "Flux cluster directory structure" section and the "Generate Flux configurations". To which section would you like me to add additional clarification?

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-:-MW3BG6UCFFaVYrHRxeC:bx7gh3a)* status: all files reviewed, 5 unresolved discussions (waiting on @jschummer and @lassemaatta)

___
*[kubernetes.sh, line 48 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MVpw-L1DQjSXvQD-N07:-MW40GLe45rw4L-1rGIM:bm5m5an) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3e5b83ac13cb30786d4c14aaff6b63d923e169f5/kubernetes.sh#L48)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

In the previous revision reviewable rendered "..." which I assume meant that there was unnecessary whitespace on an empty line. But now it seems it's gone in the latest revision.
</blockquote></details>

OK, good!
___
*[kubernetes.sh, line 16 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MW32iqa02d6FEpbq8cT:-MW3CIlX99NKvTRNNPz2:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/29e6a1945301a733f607c8c8d4133590bd3d95af/kubernetes.sh#L16)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> $(kubectl config current-context)
> ```
Slightly cleaner solution would be to run the command once and store the output in a variable.
</blockquote></details>

Done.
___
*[README.md, line 439 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MW33YF20XdSV0XHCP6N:-MW3Cgn-6bS3ynGFiBu2:bkroxro) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/29e6a1945301a733f607c8c8d4133590bd3d95af/README.md#L439)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> periodically
> ```
Would maybe good to state the interval. 1s, 5s, 1 min, 60 h? May make a big difference.
</blockquote></details>

well, it comes from the configuration... but I can write the current value to the README
___
*[README.md, line 466 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MW33slC7rH0DthHgxSi:-MW3D3_EC4MXvh0X2Fet:b-41xeon) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/29e6a1945301a733f607c8c8d4133590bd3d95af/README.md#L466)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> :dev/:test/:prod)
> ```
I'd prefere if we could make this work without general release docker tags. So instead of deploying tag :prod over and over again, we'd explicitly update the kube config to first deploy tag :prod-1.0, then later :prod-1.1 and so on.

Is this possible? If so, could you update this example?
</blockquote></details>

It's of course possible, but not in the scope of this pull request. I'll update this README with the tagging strategy whenever we have something concrete 
___
*[README.md, line 477 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MW34HVG9Q2ggokcjGAO:-MW4099M0h9ONKyQHCzF:b-aduc6s) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/29e6a1945301a733f607c8c8d4133590bd3d95af/README.md#L477)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Maybe could specify which is the directory containing the bootstrapped files, i.e. which contents shouldn't be modified manually?
</blockquote></details>

This is already described in the "Flux cluster directory structure" section, are you missing something from there?

**Review by jschummer — CHANGES_REQUESTED** [review]
Like mentioned below, I'd appreciate some clarification in the "Generate Flux configurations"-section. Additionally the list of directories containing generated code could be listed in the commit message.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-:-MW47QvDCXWvejoCEfyQ:bqyx4zv)* status: 28 of 30 files reviewed, 2 unresolved discussions (waiting on @jschummer, @lassemaatta, and @pallost)

___
*[README.md, line 466 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MW33slC7rH0DthHgxSi:-MW48Tcj7JF5gq3xVOFf:b-grwvy) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/29e6a1945301a733f607c8c8d4133590bd3d95af/README.md#L466)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

It's of course possible, but not in the scope of this pull request. I'll update this README with the tagging strategy whenever we have something concrete 
</blockquote></details>

Ok. I fear that from this README line one might get the idea that there is those three mentioned choices (:dev/:test/:prod), in that sense I would prefer it to mention an example which could not be as easily mistaken. For example
```
hsldevcom/jore4-frontend:dev-example-tag-4f0127be
```

Do you think you could change it to avoid misunderstandings, even though our tag structure has not been decided yet?
___
*[README.md, line 477 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MW34HVG9Q2ggokcjGAO:-MW49dnk7QVnUz0pQvVQ:bjn9c6t) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/29e6a1945301a733f607c8c8d4133590bd3d95af/README.md#L477)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

This is already described in the "Flux cluster directory structure" section, are you missing something from there?
</blockquote></details>

Maybe I didn't state clear enough that I would find it useful to know which files have been generated (by the bootstrap process) and by which command exactly.

Some commands are mentioned in the "Generate Flux configurations" section, but it sounds like these are mentioned for future use. Are these the same commands that have been used to generate the files included in this PR? If so, maybe you could bring that out more clearly in that section.

And maybe the info about which files / dirs were generated could additionally be added to the commit message, so someone using e.g. `git whatchanged` can immediately spot manually made changes and generated ones.

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9)* status: 28 of 30 files reviewed, 2 unresolved discussions (waiting on @jschummer and @lassemaatta)

___
*[README.md, line 466 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MW33slC7rH0DthHgxSi:-MW4E4XX-X0h7tFvv-fS:b-3hbiaq) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/29e6a1945301a733f607c8c8d4133590bd3d95af/README.md#L466)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Ok. I fear that from this README line one might get the idea that there is those three mentioned choices (:dev/:test/:prod), in that sense I would prefer it to mention an example which could not be as easily mistaken. For example
```
hsldevcom/jore4-frontend:dev-example-tag-4f0127be
```

Do you think you could change it to avoid misunderstandings, even though our tag structure has not been decided yet?
</blockquote></details>

ok, it's true that it could be misleading about what we are aiming for here. I'll fix it
___
*[README.md, line 477 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9#-MW34HVG9Q2ggokcjGAO:-MW4F22U1D7K4OpAp0Ni:bxb4sq0) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/29e6a1945301a733f607c8c8d4133590bd3d95af/README.md#L477)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Maybe I didn't state clear enough that I would find it useful to know which files have been generated (by the bootstrap process) and by which command exactly.

Some commands are mentioned in the "Generate Flux configurations" section, but it sounds like these are mentioned for future use. Are these the same commands that have been used to generate the files included in this PR? If so, maybe you could bring that out more clearly in that section.

And maybe the info about which files / dirs were generated could additionally be added to the commit message, so someone using e.g. `git whatchanged` can immediately spot manually made changes and generated ones.
</blockquote></details>

OK, I added clarifying text on what was generated and what wasn't. But it's kinda misleading, because generating here only means that we used a CLI command to create a config file that we could've just easily written manually ourselves. I don't want to leave an impression to future developers that they actually need to generate anything: they should just modify the existing manifest files. I only added instructions on how I generated these manifests, because that's how I got to ground zero where everything started working. However in the future I don't think anyone will/should generate anything...

**Review by jschummer — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/9)* status: all files reviewed, 1 unresolved discussion (waiting on @lassemaatta)

**Pull request merged**
