### PR TITLE
Deploy public subnet NSG only if it does not exist yet

### PR DESCRIPTION
**Pull request by jschummer**
This way, the NSG can be modified manually without the changes being
reverted the next time the rg-and-nets -playbook is run.

This can be used to configure custom IP ranges in the public subnet NSG
for bastion host access.

Fixes HSLdevcom/jore4#83

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33)

### CODE REVIEW

**Review by tk-vincit — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @jschummer)

___
*[ansible/roles/azure_network/tasks/public-subnet-nsg.yml, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYJ8oG92jBJeB-KY5Xx:-MYJ8oGAEHxM12njDgpO:b4mqegi) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5b333e17e901e3c2277a3c6356f82fac84b243e4/ansible/roles/azure_network/tasks/public-subnet-nsg.yml#L7)):*
> ```YAML
> 
> - debug:
>     msg: "{{ nsg_id.stdout }}"
> ```

I assume we are doing some kind of debug logging here? Should we also log _what_ we are logging to improve readability? I mean, something like: "Security group \"{{ az_resource_group_name }}\" name: "\{{ nsg_id.stdout }} \""
___
*[ansible/roles/azure_network/tasks/public-subnet-nsg.yml, line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYJ9OsL0vxL0C8iyGA4:-MYJ9OsL0vxL0C8iyGA5:b-pgy0ya) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5b333e17e901e3c2277a3c6356f82fac84b243e4/ansible/roles/azure_network/tasks/public-subnet-nsg.yml#L14)):*
> ```YAML
>     resource_group: "{{ az_resource_group_name }}"
>     location: "{{ az_region_name }}"
>     name: "azure_network_common"
> ```


Should this be defined as in `ansible/groups_vars/all.yml`?
`"{{ az_project_name }}-common"` instead of `"azure_network_common"`
___
*[ansible/roles/azure_network/tasks/public-subnet-nsg.yml, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYJ9uI2-lygOfdtHu_H:-MYJ9uI2-lygOfdtHu_I:b-kzndr6) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5b333e17e901e3c2277a3c6356f82fac84b243e4/ansible/roles/azure_network/tasks/public-subnet-nsg.yml#L23)):*
> ```YAML
>         value: "{{ az_public_nsg_name }}"
>     tags:
>       ansible: "workaround"
> ```

Sounds like something that is going to raise questions in future :) 
___
*[ansible/templates/public-subnet-nsg.arm.json, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYJAICl2rBlTffld4JL:-MYJAICm3P7e1Fv-seXD:bl8gjn8) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5b333e17e901e3c2277a3c6356f82fac84b243e4/ansible/templates/public-subnet-nsg.arm.json#L8)):*
> ```JSON
>       "type": "string",
>       "metadata": {
>         "description": "The short name of the project. Usually same as the name of the subscription in Azure."
> ```

Is this generated code or something? This description won't help us at all. :)

**Review by pallost — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @jschummer and @tk-vincit)

___
*[ansible/roles/azure_network/tasks/main.yml, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYJHnx139Cu_zI27MK-:-MYJHnx139Cu_zI27MK0:b3eikd4) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5b333e17e901e3c2277a3c6356f82fac84b243e4/ansible/roles/azure_network/tasks/main.yml#L7)):*
> ```YAML
>   when: not cidr_prefix is regex("[0-9]{1,3}[.][0-9]{1,3}[.][0-9]{1,3}")
> 
> - include_tasks: public-subnet-nsg.yml
> ```

we've talked with @jschummer that rather than cutting the ARM template to two parts, could just use a conditional section in the ARM template, like this: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/conditional-resource-deployment?tabs=json
___
*[ansible/roles/azure_network/tasks/public-subnet-nsg.yml, line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYJ9OsL0vxL0C8iyGA4:-MYJCHyD92ZiQ7foG7XH:b-s1fa8l) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5b333e17e901e3c2277a3c6356f82fac84b243e4/ansible/roles/azure_network/tasks/public-subnet-nsg.yml#L14)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>


Should this be defined as in `ansible/groups_vars/all.yml`?
`"{{ az_project_name }}-common"` instead of `"azure_network_common"`
</blockquote></details>

actually, this is named incorrectly. This current deployment deploys the public NSG to the given environment's resource group, not to the common resource group. Maybe `azure_network_public_nsg` would be a better name...?

@tk-vincit this `name` only shows in the Azure Portal Deployments log and helps us identify what deployment script we ran. We could of course use the project's name in the name, but I don't see an advantage in it.
___
*[ansible/roles/azure_network/tasks/public-subnet-nsg.yml, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYJ9uI2-lygOfdtHu_H:-MYJCVtg-Zn0Oros9gjS:b-m1ndul) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5b333e17e901e3c2277a3c6356f82fac84b243e4/ansible/roles/azure_network/tasks/public-subnet-nsg.yml#L23)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Sounds like something that is going to raise questions in future :) 
</blockquote></details>

yeah, I already did ask this from Jyrki :) There is a bug in the Ansible Azure plugin that erases all tags from a resource group if you don't define a tag in an azure_rm_deployment. Might be something worth commenting to the IaC code though...

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[ansible/roles/azure_network/tasks/main.yml, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYJHnx139Cu_zI27MK-:-MYJIw2Y5R_EFC18yf6n:b90bb5s) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5b333e17e901e3c2277a3c6356f82fac84b243e4/ansible/roles/azure_network/tasks/main.yml#L7)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

we've talked with @jschummer that rather than cutting the ARM template to two parts, could just use a conditional section in the ARM template, like this: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/conditional-resource-deployment?tabs=json
</blockquote></details>

Yes, I'll redo the whole shebang. Next version coming up soon :-)
___
*[ansible/roles/azure_network/tasks/public-subnet-nsg.yml, line 7 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYJ8oG92jBJeB-KY5Xx:-MYJHl3S-jDOXgKPy7Tq:bkdodce) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5b333e17e901e3c2277a3c6356f82fac84b243e4/ansible/roles/azure_network/tasks/public-subnet-nsg.yml#L7)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I assume we are doing some kind of debug logging here? Should we also log _what_ we are logging to improve readability? I mean, something like: "Security group \"{{ az_resource_group_name }}\" name: "\{{ nsg_id.stdout }} \""
</blockquote></details>

Sure, I'll add some more descriptive text. This was copied straight from some other place, until now we didn't have too verbose debug outputs :-)
___
*[ansible/roles/azure_network/tasks/public-subnet-nsg.yml, line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYJ9OsL0vxL0C8iyGA4:-MYJHz9yA3_NGZTULkuM:b-7vlh4b) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5b333e17e901e3c2277a3c6356f82fac84b243e4/ansible/roles/azure_network/tasks/public-subnet-nsg.yml#L14)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

actually, this is named incorrectly. This current deployment deploys the public NSG to the given environment's resource group, not to the common resource group. Maybe `azure_network_public_nsg` would be a better name...?

@tk-vincit this `name` only shows in the Azure Portal Deployments log and helps us identify what deployment script we ran. We could of course use the project's name in the name, but I don't see an advantage in it.
</blockquote></details>

This is the name of the deployment, not the name of the resource. So in that sense it is not necessary that it contains the project name, but like pallost pointed out, another name would be better in any case.
___
*[ansible/roles/azure_network/tasks/public-subnet-nsg.yml, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYJ9uI2-lygOfdtHu_H:-MYJIba819nUccvgI_aK:b-8t3xqj) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5b333e17e901e3c2277a3c6356f82fac84b243e4/ansible/roles/azure_network/tasks/public-subnet-nsg.yml#L23)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

yeah, I already did ask this from Jyrki :) There is a bug in the Ansible Azure plugin that erases all tags from a resource group if you don't define a tag in an azure_rm_deployment. Might be something worth commenting to the IaC code though...
</blockquote></details>

Yes, I thought I could add a line to our README about this. Will be in a separate commit (same PR though).
___
*[ansible/templates/public-subnet-nsg.arm.json, line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYJAICl2rBlTffld4JL:-MYJIjh5Alh_jyWlW13k:bo2yzl8) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/5b333e17e901e3c2277a3c6356f82fac84b243e4/ansible/templates/public-subnet-nsg.arm.json#L8)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Is this generated code or something? This description won't help us at all. :) 
</blockquote></details>

It's copied from our other templates :-) And I don't find it too bad a description. I'd just check in Azure what our subscription name is and use that here.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @jschummer, @pallost, and @tk-vincit)

___
*[README.md, line 108 at r3](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYOQh1W3zGaayxu7W6j:-MYOQh1W3zGaayxu7W6k:bjpt4d7) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/92ad468771feb868d8dc9594ed4c0d7521ab0993/README.md#L108)):*
> ```Markdown
> If the given resources with the same name already exist, they are overwritten with the resources
> described by the scripts. Other resources are not modified or delete unless explicitly mentioned in
> the script description. One exception to this is the public NSG, which is only deployed if it does
> ```

I think this rather belongs to the "Provisioning resource groups and network" section, that is where most people would look for network-related information.

I would also rephrase it like this:
One exception to this is the public network security group (NSG), which is only deployed if it does not exist yet. This allows for manual modifications like custom firewall settings to survive later re-deployments.

**Review by jschummer — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-:-MYOjZdN33Jqk_KRyW_C:bnfp4nl)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @jschummer, @pallost, and @tk-vincit)

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[README.md, line 108 at r3](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYOQh1W3zGaayxu7W6j:-MYOjbPUADSqQ7-_ixZr:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/92ad468771feb868d8dc9594ed4c0d7521ab0993/README.md#L108)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I think this rather belongs to the "Provisioning resource groups and network" section, that is where most people would look for network-related information.

I would also rephrase it like this:
One exception to this is the public network security group (NSG), which is only deployed if it does not exist yet. This allows for manual modifications like custom firewall settings to survive later re-deployments.
</blockquote></details>

Done.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @pallost and @tk-vincit)

**Review by tk-vincit — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @jschummer and @pallost)

___
*[README.md, line 93 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYd-dIz-0kb5mFjuKBz:-MYd-dIz-0kb5mFjuKC-:bzh5f7v) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/e78050b7769a795850e8362d95293c258c8e6863/README.md#L93)):*
> ```Markdown
> context by using: `az account set --subscription "jore4"`
> 
> Note that `start-ansible-shell.sh` and `kubernetes.sh` automatically does this for you.
> ```

*do this for you? :wink: 
Non-blocker as this line seems just to be moved from another place to here in this commit.
___
*[README.md, line 115 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYd-toB9e1bdJLNvHGw:-MYd-toB9e1bdJLNvHGx:bg7yowh) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/e78050b7769a795850e8362d95293c258c8e6863/README.md#L115)):*
> ```Markdown
> 
> Note that in ARM deployments, the `ansible: workaround` tag has to be used in order to prevent the
> removal of all tags of the resource group due to a bug in the ansible ARM plugin.
> ```

When that "removal of all tags" would happen?

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[README.md, line 93 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYd-dIz-0kb5mFjuKBz:-MYd6p1K4PO_XsBcldRG:b-v1pxhm) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/e78050b7769a795850e8362d95293c258c8e6863/README.md#L93)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

*do this for you? :wink: 
Non-blocker as this line seems just to be moved from another place to here in this commit.
</blockquote></details>

Might be better, but like you wrote, that line wasn't created in this PR :-/ So I'd leave it like that for now.
___
*[README.md, line 115 at r4](https://reviewable.io/reviews/hsldevcom/jore4-deploy/33#-MYd-toB9e1bdJLNvHGw:-MYd6ySs1ywmo3dKeTYY:b-5iqpzo) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/e78050b7769a795850e8362d95293c258c8e6863/README.md#L115)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

When that "removal of all tags" would happen?
</blockquote></details>

I think it is quite clear, because ARM deployments are mentioned. So I don't think it adds much value to add "when the ARM deployments are applied".

Also I just realized that I already integrated these changes when I got pallost's approval last week... :grimacing:

**Pull request closed without merging**
