### PR TITLE
Generate passwords for db users without special characters

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/44)

### CODE REVIEW

**Review by lassemaatta — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/44)* status: all files reviewed, 1 unresolved discussion (waiting on @pallost)

___
*[README.md, line 206 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/44#-Mb5kREjBFZk98bRrfMn:-Mb5kREkDWOJXudcEvQt:bcthbuz) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/6afb45e58220a7e4d31d1884ddee9fa6b19908f5/README.md#L206)):*
Perhaps add an example here, because the README states later that 

> As the full playbook is quite long, you may use the following tags to limit the parts you want to
execute:

which might make someone ask "do I need to run the whole aks playbook or can I just run the `keyvault-identity-binding` tag?"

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/44)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @lassemaatta)

___
*[README.md, line 206 at r1](https://reviewable.io/reviews/hsldevcom/jore4-deploy/44#-Mb5kREjBFZk98bRrfMn:-MbBN3-A3Vl5QAsgxlHf:b-b68nq9) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/6afb45e58220a7e4d31d1884ddee9fa6b19908f5/README.md#L206)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

Perhaps add an example here, because the README states later that 

> As the full playbook is quite long, you may use the following tags to limit the parts you want to
execute:

which might make someone ask "do I need to run the whole aks playbook or can I just run the `keyvault-identity-binding` tag?"

</blockquote></details>

Good point! You only need the identity binding part. Fixed it!

**Review by lassemaatta — COMMENTED** [review]
Looks ok to me, but perhaps someone else should also check this out.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/44#-:-MbBNdQUC4XZE_rCqv8T:b-3di4on)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pallost)

**Review by tk-vincit — APPROVED** [review]
Looks good to me too.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/44#-:-MbBOltg6Vq1UO84HgSe:b-c1p1ip)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pallost)

**Review by haphut — APPROVED** [review]
Looks good!

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/44#-:-MbFIchB3abPh-D8SZqv:b-vs1prh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pallost)

___
*[README.md, line 206 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/44#-MbFIKdn9cZK5QOZJdCh:-MbFIKdn9cZK5QOZJdCi:bugobdp) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3135d6a7a91f93164753192f610f3d2725c8e1f8/README.md#L206)):*
> ```Markdown
> _Note that when rerunning this playbook, the vault-user binding with AKS breaks. To fix it, you need
> to rerun the AKS playbook identity binding part:
> `playdev play-provision-aks.yml --tags keyvault-identity-binding`_
> ```

What does the `_` do at the end of the line?

**Review by lassemaatta — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-deploy/44)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pallost)

___
*[README.md, line 206 at r2](https://reviewable.io/reviews/hsldevcom/jore4-deploy/44#-MbFIKdn9cZK5QOZJdCh:-MbFT7Ax0MkRUYfGQ-L-:b-m014qc) ([raw file](https://github.com/hsldevcom/jore4-deploy/blob/3135d6a7a91f93164753192f610f3d2725c8e1f8/README.md#L206)):*
<details><summary><i>Previously, haphut wrote…</i></summary><blockquote>

What does the `_` do at the end of the line?
</blockquote></details>

The whole paragraph is in _italics_, note the `_` at the beginning.

**Pull request merged**
